<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/styleJavaScript.css">
    <title>Error</title>
</head>

<body>
    <main>
        <h1>Error</h1>
        <p class="expText">There are two types of errors: <ol>
                <li>syntax error (code dose not work)</li>
                <li>logical error (code works but not as intended)</li>
            </ol>
        </p>

        <h2>finding syntax errors</h2>
        <!-- onerror (window.onerror) //////////////////////////////////////////////////////////////////////////////// -->
        <h3>onerror (window.onerror)</h3>
        <p class="expText">Triggers a before defined function with the information of the error, <b>if</b> an error
            occurs.</p>
        <ul>
            <li>When a <b>JavaScript runtime error</b> occurs, an error event is "fired" at window.</li>
            <li>A (in the head declared) function can be assigned to <code>onerror</code>, the function is than invoked
                if an
                error occurs.</li>
            <li>The parameters of the function are filled with the information of the error.</li>
        </ul>
        <ol>
            <li>declare function<br><code>function errorMessage(message, source,
                    lineno, colno, error) { ... };</code>
                <ul>
                    <li>The name of the function and its arguments is arbitrary.</li>
                    <li>The order can not be changed, arguments can be omitted from the end.</li>
                </ul>
                <ol>
                    <li><code>message</code> error message (string).</li>
                    <li><code>source</code> URL of the script where the error was raised (string)</li>
                    <li><code>lineno</code> Line number where error was raised (number)</li>
                    <li><code>colno</code> Column number for the line where the error occurred (number)</li>
                    <li><code>error</code> Error Object (object)</li>
                </ol>
            <li>assign the function (<code>window.</code> can be omitted)<br><code>onerror = errorMessage;</code></li>
        </ol>
        </p>
        <details>
            <summary></summary>
            <pre class="exCode">
...
   &lt;script>
      function errorMessage(message, source, lineno, colno, error) {
         alert("error message: " + message + "\nsource: " + source +
            "\nlineno: " + lineno + "\ncolumn: " + colno + "\nerror: " + error);
      }
   &lt;/script>
&lt;/head>

&lt;body>
   &lt;p>
      &lt;script>
         onerror = errorMessage;
         const y = 42;
         //     const x = 11; // is not declared, which courses the error
         document.write(x + "&lt;br>");
         document.write(y + "&lt;br>");
      &lt;/script>
   &lt;/p>
&lt;/body></pre>
            <img src="/images/error/onerror.svg" alt="">
        </details>
        <a href="/html/javaScript/zExampleCodeJavaScript/zExampleCodeOnerror.htm" target="_blank">see example page</a>
        <!-- try … catch ///////////////////////////////////////////////////////////////////////////////////////////// -->
        <h3>try … catch (exception handling)</h3>
        <p class="expText">Code which is contained within a "try-block" can in case of an error, return a specific error
            message or follow for that case specified instructions. The code in the "finally-block" is executed in an
            case.</p>
        <ol>
            <li>contain the buggy code in the "try-block"<br>
                <code>try { BUGGY CODE; }</code>
            </li>
            <li>set up the "catch-block" and process the error message<br>
                <code>catch(<mark title="error object, usually e (error) but it could have any arbitrary name">e</mark>)
                    {
                    alert(<mark title="the error object is passed to the alert() method">e</mark>); }</code></li>
            <li>(optional) set the "finally-block", which is executed in any case<br><code>finally { STATEMENT; }</code>
            </li>
        </ol>
        <ul>
            <li>none of the "blocks" have a <code>;</code> at the end</li>
        </ul>
        <details>
            <summary></summary>
            <pre class="exCode">
    &lt;script>
        const y = 42
        // const x = 66 //is missing which course the error
        try {
           document.write(x + "&lt;br>");
           document.write(y + "&lt;br>");
        } catch (e) {
           alert(e);
        } finally {
           document.write("This line is written in any case.&lt;br>");
        }
    &lt;/script></pre><img src="/images/error/tryCatch.svg" alt="">
        </details>
        <a href="/html/javaScript/zExampleCodeJavaScript/zExampleCodeTry_catch.htm" target="_blank">see example page</a>
        <!-- throw (throws to catch) ///////////////////////////////////////////////////////////////////////////////////// -->
        <h3>throw (throws to catch)</h3>
        <p class="expText">Statements which are marked with <code>throw</code> and are contained within the "try-block"
            are passed to the "catch-block".</p>
        <ol>
            <li>mark the statement which should be <code>throw</code>n to the "catch-block" in the "try-block"
                <pre><code>
try { if (CONDITION1) throw STATEMENT1;
      if (CONDITION2) throw STATEMENT2; }</code></pre>
            </li>
            <li>only the statement marked with throw is passed to the "catch-block"<br>
                <code>catch(<mark title="error object, usually e (error) but it could have any arbitrary name">e</mark>)
                    {
                    alert(<mark title="the error object is passed to the alert() method">e</mark>); }</code></li>
            <li>(optional) set the "finally-block", which is executed in any case<br><code>finally { STATEMENT; }</code>
            </li>
        </ol>
        <ul>
            <li>none of the "blocks" have a <code>;</code> at the end</li>
        </ul>
        <details>
            <summary></summary>
            <pre class="exCode">
&lt;script>
   const number = parseFloat(prompt(
      "Please, enter a number > 0."))   //wrong user input courses error

   try {
      if (isNaN(number))                //if not a number the following
         throw "Not a valid number.";   //statement is returned
      if (number &lt;= 0)                  //if number is smaller than 0 the following
         throw "Number to small.";      //statement is returned
      document.write("Number: " + number);
   } catch (errorObject) {
      alert(errorObject);
   }
&lt;/script></pre><img src="/images/error/throw.svg" alt="">
        </details>
        <a href="/html/javaScript/zExampleCodeJavaScript/zExampleCodeThrow.htm" target="_blank">see example page</a>
    </main>
</body>

</html>